WebMobilProgramlama/Models/Model1.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMobilProgramlama.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database1Entities : DbContext
    {
        public Database1Entities()
            : base("name=Database1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Table> Table { get; set; }
    }
}

WebMobilProgramlama/Models/Model1.Designer.cs
// T4 code generation is enabled for model 'C:\Users\Dell\Desktop\Yazılım\C# Projects\WebMobilProgramlama\Models\Model1.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

WebMobilProgramlama/Models/Model1.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

WebMobilProgramlama/Models/Table.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMobilProgramlama.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int ilplaka { get; set; }
        public string ilad { get; set; }
    }
}

WebMobilProgramlama/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebMobilProgramlama.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

    }
}

WebMobilProgramlama/Controllers/TablesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebMobilProgramlama.Models;

namespace WebMobilProgramlama.Controllers
{
    public class TablesController : Controller
    {
        private Database1Entities db = new Database1Entities();

        // GET: Tables
        public ActionResult Index()
        {   
            int saat = DateTime.Now.Hour;
            string selam = saat > 12 ? (saat > 17 ? "İyi Akşamlar" : "Tünaydın") : "Günaydın";
            string now = DateTime.Now.ToString("HH:mm");

            ViewBag.mesaj = $"{selam} – Saat: {now}";

            return View(db.Table.ToList());
        }

        // GET: Tables/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Table table = db.Table.Find(id);
            if (table == null)
            {
                return HttpNotFound();
            }
            return View(table);
        }

        // GET: Tables/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Tables/Create
        // Aşırı gönderim saldırılarından korunmak için bağlamak istediğiniz belirli özellikleri etkinleştirin. 
        // Daha fazla bilgi için bkz. https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ilplaka,ilad")] Table table)
        {
            if (ModelState.IsValid)
            {
                db.Table.Add(table);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(table);
        }

        // GET: Tables/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Table table = db.Table.Find(id);
            if (table == null)
            {
                return HttpNotFound();
            }
            return View(table);
        }

        // POST: Tables/Edit/5
        // Aşırı gönderim saldırılarından korunmak için bağlamak istediğiniz belirli özellikleri etkinleştirin. 
        // Daha fazla bilgi için bkz. https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ilplaka,ilad")] Table table)
        {
            if (ModelState.IsValid)
            {
                db.Entry(table).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(table);
        }

        // GET: Tables/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Table table = db.Table.Find(id);
            if (table == null)
            {
                return HttpNotFound();
            }
            return View(table);
        }

        // POST: Tables/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Table table = db.Table.Find(id);
            db.Table.Remove(table);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebMobilProgramlama/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

WebMobilProgramlama/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

WebMobilProgramlama/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

WebMobilProgramlama/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ASP.NET Uygulamam</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Uygulama adı", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Gezintiyi aç/kapat" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Giriş", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Hakkında", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Kişi", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("İl Tablosu", "Index", "Tables", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - ASP.NET Uygulamam</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebMobilProgramlama/Views/Tables/Create.cshtml
@model WebMobilProgramlama.Models.Table
@{
    ViewBag.Title = "Yeni İl";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="mb-4">Yeni İl Oluştur</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="row g-3">
        <div class="col-sm-4">
            @Html.LabelFor(m => m.ilplaka, new { @class = "form-label" })
            @Html.EditorFor(m => m.ilplaka, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(m => m.ilplaka, "", new { @class = "text-danger small" })
        </div>

        <div class="col-sm-8">
            @Html.LabelFor(m => m.ilad, new { @class = "form-label" })
            @Html.EditorFor(m => m.ilad, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(m => m.ilad, "", new { @class = "text-danger small" })
        </div>

        <div class="col-12">
            <button type="submit" class="btn btn-primary">Kaydet</button>
            @Html.ActionLink("Vazgeç", "Index", null,
                new { @class = "btn btn-outline-secondary ms-2" })
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebMobilProgramlama/Views/Tables/Delete.cshtml
@model WebMobilProgramlama.Models.Table
@{
    ViewBag.Title = "İl Sil";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="mb-3 text-danger">İli Sil</h2>
<p class="mb-4">Bu kaydı silmek istediğinize emin misiniz?</p>

<div class="alert alert-light border mb-4" style="max-width: 420px;">
    <strong>@Model.ilad</strong> (@Model.ilplaka)
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <button type="submit" class="btn btn-danger">Evet, Sil</button>
    @Html.ActionLink("Vazgeç", "Index", null,
        new { @class = "btn btn-outline-secondary ms-2" })
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebMobilProgramlama/Views/Tables/Details.cshtml
@model WebMobilProgramlama.Models.Table
@{
    ViewBag.Title = "İl Detayları";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="mb-4">İl Detayları</h2>

<div class="card shadow-sm mb-3" style="max-width: 420px;">
    <div class="card-body">
        <h5 class="card-title mb-3">@Model.ilad</h5>
        <p class="card-text"><strong>Plaka Kodu:</strong> @Model.ilplaka</p>
    </div>
</div>

@Html.ActionLink("Düzenle", "Edit",
    new { id = Model.ilplaka }, new { @class = "btn btn-outline-secondary me-2" })
@Html.ActionLink("Geri Dön", "Index", null, new { @class = "btn btn-outline-primary" })

WebMobilProgramlama/Views/Tables/Edit.cshtml
@model WebMobilProgramlama.Models.Table
@{
    ViewBag.Title = "İl Düzenle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="mb-4">İli Düzenle</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.ilplaka)

    <div class="row g-3">
        <div class="col-sm-8 col-md-6 col-lg-4">
            @Html.LabelFor(m => m.ilad, new { @class = "form-label" })
            @Html.EditorFor(m => m.ilad, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(m => m.ilad, "", new { @class = "text-danger small" })
        </div>

        <div class="col-12">
            <button type="submit" class="btn btn-primary">Kaydet</button>
            @Html.ActionLink("İptal", "Index", null,
                new { @class = "btn btn-outline-secondary ms-2" })
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebMobilProgramlama/Views/Tables/Index.cshtml
@model IEnumerable<WebMobilProgramlama.Models.Table>
@{
    ViewBag.Title = "İller";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="d-flex justify-content-between align-items-center mb-3">
    <h2 class="mb-0">İller</h2>
    @Html.ActionLink("Yeni İl Ekle", "Create", null,
        new { @class = "btn btn-primary" })
</div>
<div class="alert alert-info mb-3">
    @ViewBag.mesaj
</div>
<table class="table table-striped table-hover align-middle">
    <thead class="table-dark">
        <tr>
            <th>@Html.DisplayNameFor(m => m.First().ilad)</th>
            <th class="text-end">İşlemler</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.ilad</td>
                <td class="text-end">
                    @Html.ActionLink("Düzenle", "Edit",
                        new { id = item.ilplaka }, new { @class = "btn btn-sm btn-outline-secondary me-1" })
                    @Html.ActionLink("Detay", "Details",
                        new { id = item.ilplaka }, new { @class = "btn btn-sm btn-outline-info me-1" })
                    @Html.ActionLink("Sil", "Delete",
                        new { id = item.ilplaka }, new { @class = "btn btn-sm btn-outline-danger" })
                </td>
            </tr>
        }
    </tbody>
</table>